spring.application.name=backend
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost/apiconsultas?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

spring.web.error.include-stacktrace=never
